name       : plplot
version    : 5.15.0
release    : 9
source     :
    - https://netix.dl.sourceforge.net/project/plplot/plplot/5.15.0%20Source/plplot-5.15.0.tar.gz : b92de4d8f626a9b20c84fc94f4f6a9976edd76e33fb1eae44f6804bdcc628c7b
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : PLplot is a cross-platform software package for creating scientific plots.
description: |
    PLplot is a cross-platform software package for creating scientific plots whose (UTF-8) plot symbols and text are limited in practice only by what Unicode-aware system fonts are installed on a user's computer. The PLplot software, which is primarily licensed under the LGPL, has a clean architecture that is organized as a core C library, separate language bindings for that library, and separate device drivers that are dynamically loaded by the core library which control how the plots are presented in noninteractive and interactive plotting contexts.
builddeps  :
    - pkgconfig(gsl)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/lib/*.a
